default:
  image: nixos/nix:latest
  before_script:
    - nix-env -iA cachix -f https://cachix.org/api/v1/install
    - nix-env -iA awscli -f '<nixpkgs>'
    - cachix use srid
    - cachix use smatting

# rib:
#   before_script:
#     - nix-build neuron.nix
#   script:
#     - ./result/bin/neuron rib -d .
#   stage: build

aws:
  script:
    - mkdir ./foo
    - echo "ha" > ./foo/bla.txt
    - aws s3 sync ./foo $BUCKET
  stage: deploy
